name: Build and Push Backend Image

on:
  # Disparador 1: Se ejecuta al hacer push a la rama 'main',
  # pero solo si hay cambios en la carpeta 'backend/'
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install -r requirements.txt
          pip install pytest

      - name: Running pytest
        working-directory: ./backend
        run: |
          pytest test_main.py

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Extrae metadatos y genera las etiquetas automáticamente
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/backend

      # 4. Construye la imagen y la publica en un solo paso
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}